services:
  web:
    image: running-calendar:latest
    container_name: running-calendar
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      POCKETBASE_URL: http://pocketbase2:8090
      POCKETBASE_ADMIN_COLLECTION: admins
      SITE_URL: https://running.madebynz.xyz
    ports:
      - "127.0.0.1:5678:3000"
    networks:
      - running-net

networks:
  running-net:
    external: true
